Repository atomist/automation-client, pull requests merged in 2018-11, with the labels that each got.

#396 Fingerprint api docs added
  lib/project/fingerprint/Fingerprint.ts
Labels: changelog:added

#401 Update to latest graphql-code-generator
  bin/gql-gen.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#402 Add review comment sorter
  index.ts
  lib/operations/review/ReviewResult.ts
  test/operations/review/ReviewResult.test.ts
Labels: auto-merge:on-approve, changelog:added

#399 Add initial Gitlab support
  index.ts
  lib/operations/common/AbstractRemoteRepoRef.ts
  lib/operations/common/BitBucketRepoRef.ts
  lib/operations/common/BitBucketServerRepoRef.ts
  lib/operations/common/GitlabPrivateTokenCredentials.ts
  lib/operations/common/GitlabRepoRef.ts
  lib/operations/common/RepoId.ts
  lib/operations/common/gitlabRepoLoader.ts
  lib/operations/common/params/GitlabTargetsParams.ts
  lib/operations/generate/GitlabRepoCreationParameters.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#409 Extract creation of HTTP and WS clients for registration to proper factories
  index.ts
  lib/configuration.ts
  lib/internal/transport/websocket/WebSocketClient.ts
  lib/internal/util/string.ts
  lib/onCommand.ts
  lib/spi/http/axiosHttpClient.ts
  lib/spi/http/httpClient.ts
  lib/spi/http/wsClient.ts
  lib/util/retry.ts
  test/configuration.test.ts
Labels: auto-merge:on-approve, changelog:changed
