Repository atomist/automation-client, pull requests merged in 2018-08, with the labels that each got.

#335 Use name to lookup graphql by operation name
  src/graph/graphQL.ts
  src/internal/graph/graphQL.ts
  src/spi/graph/GraphClient.ts
  test/graph/GraphQLTest.ts
  test/graphql/subscription/fooBar.graphql
Labels: breaking, changelog:changed, changelog:deprecated

#336 Fix type dependencies, add git-info and gql-gen
  CHANGELOG.md
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/start.git-info.ts
  src/start.gql-gen.ts
Labels: atomist:merge-on-approve

#337 Use cross-spawn to better support Windows
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/util/spawned.ts
Labels: atomist:merge-on-approve, changelog:changed

#339 Install scripts in bin
  package-lock.json
  package.json
Labels: atomist:merge-on-approve, changelog:changed

#343 Add support for proxy authentication
  src/internal/transport/websocket/WebSocketClient.ts
  src/internal/util/http.ts
Labels: changelog:added

#347 If no event handlers are found, return 404 not 500
  src/internal/transport/express/ExpressServer.ts
  src/server/AbstractAutomationServer.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#349 Remove dimensions on metrics
  src/util/statsd.ts
Labels: auto-merge:on-approve, changelog:changed
