Repository atomist/automation-client, pull requests merged in 2018-06, with the labels that each got.

#306 Sometimes we want to use curl to talk to BitBucket
  package-lock.json
  src/operations/common/BitBucketServerRepoRef.ts
  src/util/spawned.ts
Labels: atomist:auto-merge

#309 Initial support for functional event handlers
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/HandleEvent.ts
  src/SmartParameters.ts
  src/configuration.ts
  src/internal/util/string.ts
  src/onCommand.ts
  src/onEvent.ts
  test/atomist.config.ts
  test/internal/metadata/eventMetadataReadingTest.ts
Labels: atomist:merge-on-approve

#311 Add command to install kube utilities
  src/cli/commands.ts
  src/cli/kube.ts
  src/start.cli.ts
Labels: atomist:merge-on-approve, changelog:added
