Repository atomist/automation-client, pull requests merged in 2018-10, with the labels that each got.

#389 Add more exports to index
  index.ts
Labels: auto-merge:on-approve, changelog:added

#390 Scope wildcard exports having common names
  index.ts
  lib/operations/common/GitHubRepoRef.ts
  lib/operations/common/params/AlwaysAskRepoParameters.ts
  lib/operations/common/params/GitHubFallbackReposParameters.ts
  lib/operations/common/params/MappedRepoParameters.ts
  lib/operations/common/params/SourceRepoParameters.ts
  lib/operations/common/params/TargetsParams.ts
  lib/operations/common/params/validationPatterns.ts
  lib/operations/generate/NewRepoCreationParameters.ts
  lib/project/util/projectUtils.ts
  test/operations/common/params/validationPatterns.test.ts
Labels: auto-merge:on-approve, breaking, changelog:changed

#392 Remove non-SDM exports from index
  index.ts
Labels: auto-merge:on-approve, breaking, changelog:removed

#395 Exclude ingesters from gql-gen
  bin/gql-gen.ts
Labels: changelog:changed

#394 Delete out-of-date documentation
  docs/CommandHandlers.md
  docs/CommandTesting.md
  docs/Concepts.md
  docs/Decorators.md
  docs/EventHandlers.md
  docs/Handlers.md
  docs/MappedParameters.md
  docs/ProjectEditors.md
  docs/ProjectGenerators.md
  docs/ProjectOperations.md
  docs/ProjectReviewers.md
  docs/Secrets.md
  docs/images/graphiql.png
Labels: changelog:removed
