Repository atomist/automation-client, pull requests merged in 2018-09, with the labels that each got.

#352 Export all of MessageClient
  src/index.ts
  src/spi/message/MessageClient.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#350 Remove all deprecations
  src/Handlers.ts
  src/automationClient.ts
  src/configuration.ts
  src/graph/ApolloGraphClient.ts
  src/graph/graphQL.ts
  src/index.ts
  src/ingesters.ts
  src/internal/invoker/Payload.ts
  src/internal/transport/AbstractRequestProcessor.ts
  src/internal/transport/express/ExpressServer.ts
  src/internal/util/http.ts
  src/operations/generate/generatorToCommand.ts
  src/project/git/GitCommandGitProject.ts
  src/server/BuildableAutomationServer.ts
  src/spi/graph/GraphClient.ts
  src/spi/message/MessageClient.ts
  src/start.client.ts
  src/start.command.ts
  src/start.git-info.ts
  src/start.gql-gen.ts
  src/util/statsd.ts
  test/api/ApolloGraphClientTest.ts
  test/api/generatorEndToEndTest.ts
  test/atomist.config.ts
  test/command/HelloWorld.ts
  test/configurationTest.ts
  test/event/circleIngester.ts
  test/event/gitLabIngester.ts
  test/graph/GraphQLTest.ts
  test/ingestersTest.ts
  test/internal/transport/websocket/DefaultWebSocketTransportEventHandlerTest.ts
  test/operations/generate/generatorToCommandTest.ts
  test/project/git/LockfileLibraryTest.ts
  test/tree/ast/typescript/TypeScriptFileParserTest.ts
  tslint.json
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed

#354 Fail when tests fail, remove team/token
  package.json
  src/atomistWebhook.ts
  src/configuration.ts
  src/internal/transport/express/ExpressRequestProcessor.ts
  src/internal/transport/websocket/WebSocketClient.ts
  src/server/BuildableAutomationServer.ts
  test/.atomist/client.config.json
  test/atomist.config.ts
  test/atomistWebhookTest.ts
  test/configurationTest.ts
Labels: auto-merge:on-approve, changelog:fixed

#355 API pruning
  src/operations/generate/UniversalSeed.ts
  src/project/File.ts
  src/project/support/AbstractFile.ts
  src/util/constructionUtils.ts
  test/project/local/NodeFsLocalFileTest.ts
  test/project/local/NodeFsLocalProjectTest.ts
  test/project/mem/InMemoryProjectTest.ts
  test/project/util/projectUtilsTest.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#358 Set all executable bits, add directoryExistsSync
  package-lock.json
  package.json
  src/project/local/NodeFsLocalProject.ts
  test/project/local/NodeFsLocalProjectTest.ts
  test/project/utils.ts
Labels: auto-merge:on-approve

#359 Match comment to code
  src/spi/clone/DirectoryManager.ts
Labels: auto-merge:on-approve

#365 Print stack before munching error
  src/operations/common/repoUtils.ts
Labels: changelog:added

#370 Update to Winston 3 and make logging configuration explicit
  package-lock.json
  package.json
  src/action/cli/commandLine.ts
  src/automationClient.ts
  src/bin/command.ts
  src/bin/git-info.ts
  src/bin/gql-gen.ts
  src/bin/start.ts
  src/configuration.ts
  src/graph/ApolloGraphClient.ts
  src/graph/ApolloGraphClientFactory.ts
  src/index.ts
  src/internal/env/NodeConfigSecretResolver.ts
  src/internal/env/applicationEvent.ts
  src/internal/env/gitInfo.ts
  src/internal/invoker/disposable.ts
  src/internal/message/ConsoleMessageClient.ts
  src/internal/message/DebugMessageClient.ts
  src/internal/transport/AbstractRequestProcessor.ts
  src/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  src/internal/transport/cluster/ClusterWorkerRequestProcessor.ts
  src/internal/transport/express/ExpressServer.ts
  src/internal/transport/showStartupMessages.ts
  src/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
  src/internal/transport/websocket/WebSocketClient.ts
  src/internal/transport/websocket/WebSocketMessageClient.ts
  src/internal/util/logger.ts
  src/internal/util/memory.ts
  src/internal/util/shutdown.ts
  src/operations/common/BitBucketRepoRef.ts
  src/operations/common/BitBucketServerRepoRef.ts
  src/operations/common/GitHubRepoRef.ts
  src/operations/common/repoUtils.ts
  src/operations/edit/projectEditorOps.ts
  src/operations/generate/generatorUtils.ts
  src/operations/generate/remoteGitProjectPersister.ts
  src/operations/generate/support/addAtomistWebhook.ts
  src/operations/support/editorUtils.ts
  src/project/git/GitCommandGitProject.ts
  src/project/local/NodeFsLocalProject.ts
  src/project/support/AbstractProject.ts
  src/project/util/jsonUtils.ts
  src/project/util/parseUtils.ts
  src/scan.ts
  src/server/BuildableAutomationServer.ts
  src/spi/clone/CachingDirectoryManager.ts
  src/spi/clone/StableDirectoryManager.ts
  src/tree/ast/FileHits.ts
  src/tree/ast/astUtils.ts
  src/tree/ast/typescript/TypeScriptFileParser.ts
  src/util/gitHub.ts
  src/util/logger.ts
  src/util/retry.ts
  src/util/spawned.ts
  src/util/statsd.ts
  test/api/ApolloGraphClientTest.ts
  test/api/apiUtils.ts
  test/atomist.config.ts
  test/benchmark/GeneratorBenchmark.ts
  test/credentials.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed

#373 Make running git commands safer
  src/action/ActionResult.ts
  src/action/cli/commandLine.ts
  src/index.ts
  src/operations/common/BitBucketServerRepoRef.ts
  src/operations/common/GitHubRepoRef.ts
  src/operations/generate/remoteGitProjectPersister.ts
  src/operations/support/editorUtils.ts
  src/project/git/Configurable.ts
  src/project/git/GitCommandGitProject.ts
  src/project/git/GitProject.ts
  src/project/git/gitStatus.ts
  src/spi/http/curlHttpClient.ts
  src/util/exec.ts
  src/util/spawn.ts
  test/project/git/CachedGitCloneTest.ts
  test/project/git/GitCommandGitProjectTest.ts
  test/project/git/GitProjectTest.ts
  test/project/git/GitStatusTest.ts
  test/spi/clone/TmpDirectoryManagerTest.ts
  test/util/spawnTest.ts
Labels: auto-merge-method:merge, auto-merge:on-check-success, breaking, changelog:changed

#375 Upgrade tree-path library
  package-lock.json
  package.json
  src/tree/LocatedTreeNode.ts
  src/tree/ast/FileHits.ts
  src/tree/ast/FileParser.ts
  src/tree/ast/FileParserRegistry.ts
  src/tree/ast/astUtils.ts
  src/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts
  src/tree/ast/typescript/TypeScriptFileParser.ts
  test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts
  test/tree/ast/typescript/TypeScriptFileParserTest.ts
  test/tree/ast/typescript/conversionTests.ts
Labels: changelog:changed

#374 Make running git commands safer
  src/action/ActionResult.ts
  src/action/cli/commandLine.ts
  src/index.ts
  src/operations/common/BitBucketServerRepoRef.ts
  src/operations/common/GitHubRepoRef.ts
  src/operations/generate/remoteGitProjectPersister.ts
  src/operations/support/editorUtils.ts
  src/project/git/Configurable.ts
  src/project/git/GitCommandGitProject.ts
  src/project/git/GitProject.ts
  src/project/git/gitStatus.ts
  src/spi/http/curlHttpClient.ts
  src/util/exec.ts
  src/util/spawn.ts
  test/project/git/CachedGitCloneTest.ts
  test/project/git/GitCommandGitProjectTest.ts
  test/project/git/GitProjectTest.ts
  test/project/git/GitStatusTest.ts
  test/spi/clone/TmpDirectoryManagerTest.ts
  test/util/spawnTest.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, breaking, changelog:changed

#377 Replace continuation-local-storage with async hooks for better tracking across async/await calls
  lib/graph/ApolloGraphClient.ts
  lib/internal/transport/AbstractRequestProcessor.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/util/cls.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#378 Augment and organize export in index
  index.ts
  test/internal/metadata/eventMetadataReadingTest.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#381 Use os.homedir() and 127.0.0.1
  lib/configuration.ts
  test/configurationTest.ts
Labels: auto-merge:on-approve

#382 Export cross-spawn as spawn
  index.ts
  lib/util/spawn.ts
Labels: auto-merge:on-approve, changelog:added

#386 Upgrade axios to 0.19.0-beta.1
  package-lock.json
  package.json
Labels: changelog:changed
