Repository atomist/automation-client, pull requests merged in 2018-07, with the labels that each got.

#316 Deprecate atomist CLI
  src/start.cli.ts
Labels: atomist:merge-on-approve

#318 API simplification
  CHANGELOG.md
  src/operations/edit/projectEditor.ts
  src/project/Project.ts
  src/project/util/parseUtils.ts
  src/project/util/projectUtils.ts
  src/tree/ast/FileHits.ts
  src/tree/ast/astUtils.ts
  test/project/local/NodeFsLocalProjectTest.ts
  test/project/util/parseUtilsTest.ts
  test/project/utils.ts
Labels: atomist:merge-on-approve, breaking, changelog:removed

#321 HTTP client and factory abstraction
  src/configuration.ts
  src/spi/http/axiosHttpClient.ts
  src/spi/http/curlHttpClient.ts
  src/spi/http/httpClient.ts
  src/util/retry.ts
  test/configurationTest.ts
  test/spi/http/axiosHttpClientTest.ts
  test/spi/http/curlHttpClientTest.ts
Labels: atomist:merge-on-approve, changelog:added, enhancement

#323 Work around 'Type ... is not assignable to type Configuration'
  package-lock.json
  src/ingesters.ts
Labels: atomist:merge-on-approve

#324 Work around Type ... is not assignable to type Configuration'
  src/ingesters.ts
Labels: atomist:merge-on-approve

#325 Replace run.ts with start.command.ts
  src/start.command.ts
Labels: atomist:merge-on-approve, changelog:deprecated

#329 Initial support for apiKeys
  package-lock.json
  package.json
  src/automationClient.ts
  src/cli/commands.ts
  src/cli/config.ts
  src/cli/gitInfo.ts
  src/cli/kube.ts
  src/cli/run.ts
  src/configuration.ts
  src/internal/invoker/Payload.ts
  src/internal/transport/AbstractRequestProcessor.ts
  src/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  src/internal/transport/express/ExpressRequestProcessor.ts
  src/internal/transport/websocket/WebSocketClient.ts
  src/internal/util/cls.ts
  src/internal/util/logger.ts
  src/internal/util/string.ts
  src/server/BuildableAutomationServer.ts
  src/start.cli.ts
  src/start.command.ts
  src/util/statsd.ts
  test/atomist.config.ts
  test/cli/commandsTest.ts
  test/configurationTest.ts
  test/internal/invoker/BuildableAutomationServerTest.ts
  test/internal/invoker/disposableTest.ts
  test/internal/invoker/functionStyleCommandHandlerTest.ts
  test/internal/metadata/classStyleMetadataReadingTest.ts
  test/internal/transport/AbstractRequestProcessorTest.ts
  test/operations/edit/editorHandlerTest.ts
Labels: atomist:merge-on-approve, breaking, changelog:added, changelog:deprecated
