Repository atomist/automation-client, pull requests merged in 2019-05, with the labels that each got.

#527 Redact outgoing messages
  index.ts
  lib/automationClient.ts
  lib/configuration.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/transport/express/ExpressRequestProcessor.ts
  lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
  lib/internal/transport/websocket/WebSocketMessageClient.ts
  lib/operations/common/AbstractRemoteRepoRef.ts
  lib/util/logger.ts
  lib/util/redact.ts
  test/command/HelloWorld.ts
  test/configuration.test.ts
  test/internal/transport/websocket/WebSocketMessageClient.test.ts
  test/util/redact.test.ts
Labels: auto-merge:on-approve, changelog:added, enhancement

#533 Expose integration point for different statsd client libraries
  lib/configuration.ts
  lib/util/statsd.ts
  lib/util/statsdClientFactory.ts
  package-lock.json
  package.json
  test/project/git/GitProject.test.ts
  test/util/statsd.test.ts
Labels: auto-merge-method:merge, auto-merge:on-check-success, changelog:added

#546 Improvements to message sending protocol
  lib/internal/message/ConsoleMessageClient.ts
  lib/internal/message/DebugMessageClient.ts
  lib/internal/transport/AbstractRequestProcessor.ts
  lib/internal/transport/cluster/ClusterWorkerRequestProcessor.ts
  lib/internal/transport/express/ExpressRequestProcessor.ts
  lib/internal/transport/websocket/WebSocketMessageClient.ts
  lib/internal/transport/websocket/payloads.ts
  lib/metadata/automationMetadata.ts
  lib/onCommand.ts
  lib/spi/message/MessageClient.ts
  lib/spi/message/MessageClientSupport.ts
  test/command/HelloWorld.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added, enhancement

#549 Rework cluster shutdown
  lib/automationClient.ts
  lib/configuration.ts
  lib/internal/env/applicationEvent.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/transport/cluster/ClusterWorkerRequestProcessor.ts
  lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
  lib/internal/transport/websocket/WebSocketClient.ts
  lib/internal/util/poll.ts
  lib/internal/util/shutdown.ts
  lib/spi/clone/StableDirectoryManager.ts
  lib/spi/statsd/statsd.ts
  test/action/actionChaining.test.ts
  test/util/child_process.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#550 Improve cluster shutdown behavior
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#542 Add default reviewer mechanism for BitBucket
  lib/operations/common/BitBucketServerRepoRef.ts
  test/operations/common/BitBucketServerRepoRef.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, auto-rebase:on-push

#553 Allow for normal exit with async hooks
  index.ts
  lib/globals.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/transport/cluster/messages.ts
  lib/internal/transport/websocket/WebSocketClient.ts
  lib/internal/util/shutdown.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:fixed

#556 Ensure query params are passed when retrieving default reviewers
  lib/operations/common/BitBucketServerRepoRef.ts
Labels: auto-merge-method:merge, auto-merge:on-check-success, changelog:fixed

#559 Deprecate `atomist://github/default_repo_visibility` mapped parameter
  lib/decorators.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, auto-rebase:on-push, changelog:deprecated

#564 Allow configuration to be a `Promise<Configuration>`
  lib/configuration.ts
  test/asyncConfig.ts
  test/configuration.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:changed, enhancement
