Repository atomist/automation-client, pull requests merged in 2019-10, with the labels that each got.

#607 Use host configuration in Express listen call
  lib/internal/transport/express/ExpressServer.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:fixed

#609 Do not create typings dir if not creating types
  bin/gql-gen.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#614 Clean up tmp dirs on shutdown
  lib/spi/clone/StableDirectoryManager.ts
  lib/spi/clone/tmpDirectoryManager.ts
  package-lock.json
  package.json
  test/project/local/NodeFsLocalProject.test.ts
  test/project/utils.ts
  test/spi/clone/TmpDirectoryManager.test.ts
  test/spi/clone/tmpDirectoryManager.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#617 Consolidates ProjectUtils files. Resolves #229
  lib/project/local/NodeFsLocalProject.ts
  lib/project/mem/InMemoryProject.ts
  lib/project/support/projectUtils.ts
  lib/project/util/projectUtils.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#618 Switch to globby for glob matching
  lib/project/local/NodeFsLocalProject.ts
  lib/project/support/AbstractProject.ts
  package.json
  test/project/perf/diskPerformance.test.ts
  test/project/util/projectUtils.test.ts
Labels: changelog:changed

#620 Consolidate on micromatch and fast-glob
  bin/gql-gen.ts
  lib/configuration.ts
  lib/project/Project.ts
  lib/project/diff/DifferenceEngine.ts
  lib/project/local/NodeFsLocalProject.ts
  lib/project/mem/InMemoryProject.ts
  lib/project/support/AbstractProject.ts
  lib/scan.ts
  package-lock.json
  package.json
  test/project/mem/InMemoryProject.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:changed

#622 Invalidate file cache on content change
  lib/project/local/NodeFsLocalFile.ts
  lib/project/mem/InMemoryFile.ts
  lib/project/support/AbstractFile.ts
  test/project/support/AbstractProject.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, auto-rebase:on-push, changelog:fixed

#624 Add exports to index
  index.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added
