Repository atomist/automation-client, pull requests merged in 2019-04, with the labels that each got.

#499 Add web identity and identity to source map
  lib/internal/parameterPopulation.ts
  lib/internal/transport/RequestProcessor.ts
  lib/spi/message/MessageClientSupport.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, enhancement

#505 Update to latest version of @graphql-codegen
  bin/gql-gen.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed, changelog:security

#513 Create single interface for creating RemoteRepoRef
  index.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/transport/websocket/WebSocketLifecycle.ts
  lib/operations/common/AbstractRemoteRepoRef.ts
  lib/operations/common/BitBucketRepoRef.ts
  lib/operations/common/BitBucketServerRepoRef.ts
  lib/operations/common/GitHubRepoRef.ts
  lib/operations/common/GitlabRepoRef.ts
  lib/operations/common/RepoId.ts
  lib/operations/common/remoteRepoRef.ts
  test/util/logger.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#517 Consolidate and make test running smarter
  package.json
  test/api/ApolloGraphClient.test.ts
  test/api/GitProjectRemote.test.ts
  test/api/apiUtils.ts
  test/api/editorUtilsWithGitHubPullRequest.test.ts
  test/api/generatorEndToEnd.test.ts
  test/benchmark/generator.benchmark.ts
  test/bitbucket-api/BitBucketGit.test.ts
  test/bitbucket-api/BitBucketHelpers.ts
  test/bitbucket-api/generatorEndToEnd.test.ts
  test/operations/common/BitBucketServerRepoRef.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#522 Remove remoteRepoFrom
  index.ts
  lib/operations/common/remoteRepoRef.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:removed
