Repository atomist/automation-client, pull requests merged in 2019-09, with the labels that each got.

#593 Modify GitHub token pattern to match on app tokens
  lib/configuration.ts
  test/util/redact.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#595 Upgrade to graphql-codegen version 1.7.1
  bin/gql-gen.ts
  lib/operations/common/AbstractRemoteRepoRef.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#597 Add support for code reloading without restart
  bin/start-dev.ts
  lib/internal/transport/showStartupMessages.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:added, enhancement

#598 Apply target for lodash
  package.json
Labels: auto-branch-delete:on-close, auto-merge-method:squash, auto-merge:on-approve

#603 Make output less verbose during development
  lib/configuration.ts
  lib/internal/env/gitInfo.ts
  lib/internal/graph/graphQL.ts
  lib/internal/transport/AbstractRequestProcessor.ts
  lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
  lib/internal/transport/express/ExpressServer.ts
  lib/internal/transport/showStartupMessages.ts
  lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
  lib/internal/transport/websocket/WebSocketClient.ts
  lib/internal/util/memory.ts
  lib/operations/common/BitBucketRepoRef.ts
  lib/operations/common/BitBucketServerRepoRef.ts
  lib/operations/common/repoUtils.ts
  lib/project/git/GitCommandGitProject.ts
  lib/project/local/NodeFsLocalProject.ts
  lib/scan.ts
  lib/server/BuildableAutomationServer.ts
  lib/tree/ast/astUtils.ts
  lib/util/logger.ts
  lib/util/spawn.ts
  package-lock.json
  package.json
  test/atomist.config.ts
  test/configuration.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#606 Introduce caching to Project API
  lib/project/File.ts
  lib/project/HasCache.ts
  lib/project/Project.ts
  lib/project/fileGlobs.ts
  lib/project/local/NodeFsLocalProject.ts
  lib/project/mem/InMemoryProject.ts
  lib/project/support/AbstractFile.ts
  lib/project/support/AbstractProject.ts
  lib/project/util/projectUtils.ts
  lib/tree/ast/FileHits.ts
  lib/tree/ast/astUtils.ts
  package-lock.json
  package.json
  test/project/local/NodeFsLocalProject.test.ts
  test/project/mem/InMemoryProject.test.ts
  test/project/perf/diskPerformance.test.ts
  test/project/util/parseUtils.test.ts
  test/project/util/projectUtils.test.ts
  test/tree/ast/typescript/TypeScriptFileParser.test.ts
  test/tree/ast/typescript/javaScriptFileParserProject.test.ts
  test/tree/ast/typescript/typeScriptFileParserProject.test.ts
Labels: auto-branch-delete:on-close, auto-merge-method:squash, auto-merge:on-approve, changelog:added, changelog:deprecated, enhancement
