Repository atomist/automation-client, pull requests merged in 2019-03, with the labels that each got.

#483 WebSocket can be destroyed before message sent
  lib/internal/transport/websocket/WebSocketLifecycle.ts
  test/internal/transport/websocket/WebSocketMessageClient.test.ts
  test/operations/support/editorUtils.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#485 Disable TSLint on generated types
  bin/gql-gen.ts
  package-lock.json
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#488 Adds branch to BitbucketRepoRef
  lib/operations/common/BitBucketRepoRef.ts
  lib/operations/common/BitBucketServerRepoRef.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#477 Add Namespace support for Gitlab
  lib/operations/common/GitlabRepoRef.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#480 Suppress token when logging clone url
  index.ts
  lib/operations/common/AbstractRemoteRepoRef.ts
  lib/util/logger.ts
  package-lock.json
  test/util/logger.test.ts
Labels: auto-merge-method:squash

#493 Clearer description for generated repo name
  lib/operations/generate/NewRepoCreationParameters.ts
Labels: auto-merge:on-approve, changelog:changed, enhancement
