Repository atomist/automation-client, pull requests merged in 2019-02, with the labels that each got.

#475 Fix typo that crashed it
  lib/internal/invoker/disposable.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, bug, changelog:fixed

#476 Add getContentBuffer method to File
  lib/project/File.ts
  lib/project/local/NodeFsLocalFile.ts
  lib/project/mem/InMemoryFile.ts
  lib/project/support/AbstractFile.ts
Labels: auto-merge:on-approve, changelog:added, enhancement

#474 Update all deps including graphql-code-generator
  bin/gql-gen.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:changed
